export { default as Game } from './Game'
export { default as Invalid404 } from './Invalid404'
export { default as Leaderboard } from './Leaderboard'
export { default as Login } from './Login'
export { default as Profile } from './Profile'